# This file was generated by GoReleaser. DO NOT EDIT.
class Lazynpm < Formula
  desc "A simple terminal UI for git commands, written in Go"
  homepage "https://github.com/jesseduffield/lazynpm/"
  version "0.1.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jesseduffield/lazynpm/releases/download/v0.1.4/lazynpm_0.1.4_Darwin_x86_64.tar.gz"
    sha256 "59cfade7fe27da3941a8a8b82f4f4d17577accfe4e7af9d60570db0067bbbd2c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/jesseduffield/lazynpm/releases/download/v0.1.4/lazynpm_0.1.4_Linux_x86_64.tar.gz"
      sha256 "3d9322766fa9fbcfdd58279fcde769df848ab51accf78d650a2894f8fc227633"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jesseduffield/lazynpm/releases/download/v0.1.4/lazynpm_0.1.4_Linux_arm64.tar.gz"
        sha256 "4f4287f418dd7e12979ca8e0552235f1b7695b0a6ece30b3b75eaed083671d62"
      else
        url "https://github.com/jesseduffield/lazynpm/releases/download/v0.1.4/lazynpm_0.1.4_Linux_armv6.tar.gz"
        sha256 "c46303405b34921349e436e94ccbb2417c0959d0ddba60daa0d1e7cd1ef595e3"
      end
    end
  end

  def install
    bin.install "lazynpm"
  end
end
